spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/week9
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    view:
      suffix: .html

  application:
    name: AskedAndAnsweredService