create
database library
    with owner postgres;

create table authors
(
    id   bigint generated by default as identity
        constraint authors_pk
            primary key,
    name varchar not null
        constraint authors_pk_2
            unique
);

create table books
(
    id          bigint generated by default as identity
        constraint books_pk
            primary key,
    title       varchar not null,
    genre       varchar not null,
    description varchar
);

create table authors_book
(
    author_id bigint
        constraint authors_fk
            references authors,
    book_id   bigint
        constraint books_fk
            references books,
    constraint authors_book_pk
        unique (author_id, book_id)
);

create table customers
(
    id         bigint generated by default as identity
        constraint customers_pk
            primary key,
    first_name varchar not null,
    last_name  varchar not null
);

create table rent_details
(
    id          bigint generated by default as identity
        constraint rent_details_pk
            primary key,
    customer_id bigint not null
        constraint customer_fk
            references customers,
    book_id     bigint not null
        constraint book_fk
            references books,
    start_date  date   not null,
    end_date    date
);
