spring:
  datasource:
    url: jdbc:h2:mem:proddb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    jdbc:
      dialect: h2